### ISSUE TITLE
Error with Data_Fn

### ISSUE THREAD

**Issue by Charles-Adams** [James-Thorson/VAST#13]
Hi Jim
Got the following error while trying to run a dataset containing a year with 100% positive tows:
Error in Data_Fn(Version = Version, FieldConfig = FieldConfig, OverdispersionConfig = OverdispersionConfig,  : 
  Some years and/or categories have either all or no encounters, and this is not permissible when ObsModel['Link']=0

**Comment by James-Thorson** [comment]
Chuck,

The error is obviously indicating that you have either 0% or 100% encounters in one or more year, and this interferes with default delta-GLMM settings.  Specifically, I have a year intercept for each year of the encounter-probability component, and this intercept will go to +Inf or -Inf for 100% or 0% encounters, respectively, and then result in a Hessian matrix that is at best positive-semi-definite (e.g., standard error computations fail).

There are several solutions, and all are experimental:

1.  You could make the intercept for encounter probability constant over time via `Data_Fn` input `RhoConfig=c("Beta1"=3,"Beta2"=0,"Epsilon1"=0,"Epsilon2"=0)`

2.  You could make the intercept for encounter probability a IID or or random-walk random effect using `RhoConfig=c("Beta1"=1,"Beta2"=0,"Epsilon1"=0,"Epsilon2"=0)` or `RhoConfig=c("Beta1"=2,"Beta2"=0,"Epsilon1"=0,"Epsilon2"=0)`

3.  You could use a new link-function that ties together encounter probability and positive-catch-rate components, using `ObsModel[2]=1` (instead of `ObsModel[2]=0` as used by default).

Please note that none of these are "conventional" (because the conventional delta-GLMM involves an intercept for each year) but they each could avoid your problem.

jim

**Comment by James-Thorson** [comment]
I've now added more details here:  https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/What-to-do-with-a-species-with-0%25-or-100%25-encounters-in-any-year
