### ISSUE TITLE
Use discrete catchability covariate

### ISSUE THREAD

**Issue by colemonnahan** [James-Thorson/VAST#141]
I'm trying to put a catchability parameter for different gear types in a multivarate model. It looks like the only way to do this is manually construct a model matrix and then define the Map so it is estimable. In my case I only have a factor with two levels so it looks like this:

````
  Q_ik <- cbind(ifelse(Data_Geostat$Gear=='Trawl', 1, 0),
                ifelse(Data_Geostat$Gear=='Trawl', 0, 1))
....
  ## Leave the first fixed otherwise confounded with the betas 
  Map$lambda1_k <- as.factor(c(NA,1))
  Map$lambda2_k <- as.factor(c(NA,NA))
  TmbList <- Build_TMB_Fn(..., Map=Map, ...)
````
I turn off estimation of the first level because I believe otherwise it would be confounded with the global intercepts. I supposed with more levels it'd be better to use R's `model.matrix` function to generate Q_ik, so something like this

````
X <- factor(sample(size=20, 1:4, replace=TRUE))
y <- rnorm(20)
Q_ik <- model.matrix(formula(y~X-1))
````

My question is whether anyone has a better way to do this or is this the best approach?

**Comment by James-Thorson** [comment]
I think its somewhat easier to make a design matrix and then just truncate one column, instead of the full-rank design matrix and then mapping off one coefficient.  But either way will work.

I'd love to overhaul the covariate specification to allow for (1) spline responses for covariates, treating the smoother as a random effect and generating the basis using MGCV, and (2) a spatially-varying coefficient model like Bacheler (2009,2012) used to good effect.  Happy to work with anyone who's interested in doing a demo or pull-request on these!

Jim
