### ISSUE TITLE
Interpreting spatial-temporal factors

### ISSUE THREAD

**Issue by larogers123** [James-Thorson/VAST#19]
A question more than an issue:

I'm looking at multispecies models with both spatial and spatial-temporal effects. I'm having a hard time understanding the Epsilon factors and how to interpret them together with the spatial Omega terms given that the species-specific loadings on the spatial factors differ from the spatio-temporal factors. Any advice?

**Comment by James-Thorson** [comment]
Thanks for asking the question here, I'm not sure where to file responses except in the Issue Tracker...

As you know:
*  Omega is spatial variation, and the 1st factor and associated (using the PCA rotation by default) show the most important form of spatial variation, the 2nd show the next most-important, etc.
*  Epsilon is spatio-temporal variation, and the map for each year is shown as "Eps_pos..." and "Eps_pres...", as well as the average across time (which maybe I should remove, and is probably not helpful).  Loadings has similar interpretation as Omega.

For interpreting factors, I recommend:

1.  Using the Poisson-process model with `ObsModel=c(2,1)` and eliminate variation in average weight via `ObsModel=c(X,X,0,0)`, i.e., turning off Omega2 and Epsilon2.  This is most useful if Omega2 and Epsilon2 explain a small portion of variation (i.e., their covariance is small relative to Omega1 and Epsilon1 when using the Poisson-process model)
2.  Only looking at the most important factors (perhaps the first 1-3)
3.  Interpreting spatial component as "fundamental niche" (spatial constraint due to average environmental conditions) and spatio-temporal as "shared environmental responses" (the impact of unmeasured environmental drivers, influencing density via correlated life-history responses)

I'm still learning how to interpret these factor models as well -- I think community analysis includes many sources of variance, so I think the complexity is somewhat "irreducible".  Of course I'm happy to chat by email or on this thread too!
