### ISSUE TITLE
consider adding "Advanced Topics" to documentation

### ISSUE THREAD

**Issue by taylori** [James-Thorson/VAST#28]
@James-Thorson showed a way to start estimation at previously estimated parameters from Save$ParHat in west coast example.

Adding a few notes on options like that to an "Advanced Topics" section in  either the User Manual or Example Rmarkdown files could be a good way to make such information available to more advanced users.

**Comment by kellijohnson** [comment]
Advanced topics would be good, but I have found that people tend to search through the available functions first. Therefore, things like how to start estimation from `Save$ParHat` would be extremely useful to have in a function. Not sure if this would be doable for the majority of people's requests for advanced options, but I think it is worthwhile for things such as calculating updated indexes based on a new stratification (e.g., `update_stratification()`), rather than supplying the R code for how to do it based on saved output.

**Comment by James-Thorson** [comment]
@taylori, @hoyles and @kellijohnson:  I'd love some help adding a new section to the User Manual, entitled "How to implement changes" that would include things like starting from `Save$ParHat`, how to edit the `TmbList$Map` object by hand, how to input a new user-defined extrapolation grid, etc.  Any interest in discussing and/or contributing?

**Comment by taylori** [comment]
I'm happy to help although at this point my knowledge of VAST is pretty weak so my contribution might be more on the providing the novice view plus a bit of past experience on writing documentation.
Could chat about this after lunch on the 20th or would you want a conversation sooner than that?

**Comment by kellijohnson** [comment]
@James-Thorson I am happy to help as well. I should be getting back into the VAST code next week regarding my thesis chapter, so I will think then on how I can be helpful. I too am available to chat on the 20th if you want.

**Comment by James-Thorson** [comment]
I have started a "How to implement basic model changes" that I think maybe includes what you're looking for.  I'm happy to discuss what to add offline.
