### ISSUE TITLE
Covariate matrix dimension size

### ISSUE THREAD

**Issue by mcgowand** [James-Thorson/VAST#44]
Had a question about dimension sizes related to including a matrix of fixed covariates (X_xj).  The X_xj matrix has the same number of rows as spatial knots (n_x) when I would have expected it to have the same dimension as individual observations (n_i). Why is that and can you provide guidance or an example as to how one should consolidate covariate data?  Would it be okay if covariate data is indexed to observations (n_i)? Below is an example for calculating eta1_x:

Current in VAST_v2_6_0.cpp file:
Line 428:  vector<Type> eta1_x = X_xj * gamma1_j.matrix();
Line 470:  P1_i(i) = Omega1_sc(s_i(i),c_i(i)) + eta1_x(s_i(i)) + zeta1_i(i) + eta1_vc(v_i(i),c_i(i));

Proposed Change:
vector<Type> eta1_i(n_i);
eta1_i = X_ij * gamma1_j.matrix();
P1_i(i) = Omega1_sc(s_i(i),c_i(i)) + eta1_i(i) + zeta1_i(i) + eta1_vc(v_i(i),c_i(i));

**Comment by James-Thorson** [comment]
Dave,

Long story short:  If all you ever want to do is understand drivers of differences in catch rates, then you can include "density covariates" measured at each sample `i`.  However, VAST is designed to understand drivers of catch rates, and then also to predict them across space and take the sum across space as an "index of abundance".  This prediction across space means that you need the value of "density covariates" for all locations within your sampling domain.  I do this by defining "density covariates" at each knot `s` rather than each location `i`, so that I can use this value when predicting density at all locations.

Does this make sense?  Your proposed change would work, but would then be unable to predict density and calculate an index of abundance without some additional data on X_ij at every location within your domain.

**Comment by mcgowand** [comment]
Then how do you recommend setting up the density covariate matrix in R to consolidate covariate values at each location i to values at each knot s?  If it was just 1 year, would you average covariate values from location i for each knot s, interpolate the values from all locations to derive a value for each knot, or follow a 3rd approach? What about for multiple years, would you average samples for each knot across years or have a separate column for each year and set up the matrix as a 3-D array with dimensions x,t,j?

**Comment by James-Thorson** [comment]
Yes, if only one year I recommend fixing X_xj for that knot to equal the average for nearby observations. For multiple years I recommend doing this separately for each year. You can also estimate covariates as a random field using MIST but it's a long walk for a short drink.
