### ISSUE TITLE
Adding land color

### ISSUE THREAD

**Issue by EllenY** [James-Thorson/VAST#68]
How do I add color to the land when plotting the density surfaces using SpatialDeltaGLMM::PlotResultsOnMap_Fn?

I tried adding land_color="grey" but the land is still transparent.

**Comment by James-Thorson** [comment]
I think I turned that off because it wasn't working well with some of the regions being flipped over the dateline using package `maps`.  So there's no current option for shading land.  Ultimately, it would be great for someone else to chip in some code on the mapping options, but I'm not sure what to suggest in the short-term.  Sorry I don't have a better suggestion!  But I can't really commit to maintaining the plotting software at the same level as the computational parts.
